### ISSUE TITLE
Chapter 8

### ISSUE THREAD

**Issue by tylercollier** [pro-react/sample-code#1]
Hi! Overall I'm enjoying the book and finding it useful!

The sample code for chapter 8 is quite incomplete, and has bugs.

In `server.js`:

```
app.set('views', './')
```

The index view path should be `./views`, not `./`. The book has this wrong too.

In `views/index.ejs`:

```
<div id="root"><%- reactComponent %></div>
```

It should be `content`, not `reactComponent`. The book has this correct.

Most importantly, I would prefer the rest of the code from the chapter. Rendering "Hello" doesn't show us all the important things we're shown in the chapter, and unless I'm missing something, I'm expected to copy and paste from the remainder of the chapter to the files, which defeats the purpose of this repo, at least for this chapter.

**Comment by cassiozen** [comment]
Hi Tyler. Thanks for your feedback. I'm really glad that the book has been useful for you. 

You are correct - I'll update the source files and fix the reference in the book as well.

**Comment by tylercollier** [comment]
Thanks. More important to me than the corrections would be having the rest of the code from the chapter in the repo. One reason I bought the book was because of chapter 8, and I'd like to see it in action.

**Comment by hfter789** [comment]
+1. Can you add the isomorphic React + react-router example?

**Comment by cassiozen** [comment]
Hi, @hfter789 @tylercollier 

I've been working on the webpack appendix for the past few days. I should add the isomorphic example in the next few ones.

**Comment by sleemer** [comment]
Hi @cassiozen! The book is really useful, but I agree with @tylercollier - we miss the chapter 8 code sample... could you provide with update when code will be available?
