### ISSUE TITLE
Error with ContactsApp

### ISSUE THREAD

**Issue by paul-phan** [pro-react/sample-code#15]
I'm trying to practice with ContactsApp in chapter 3 and i got a problem: App.js:144 Uncaught TypeError: Cannot read property 'filter' of undefined those I checked it many times or copy your raw code in the book but it still the same. 
![screenshot 21](https://cloud.githubusercontent.com/assets/11459809/19140404/0b7d2202-8bb7-11e6-8dfc-cdae9ffa2a86.png)

Hope you support me to fix it.

**Comment by burslem2001** [comment]
Ensure that the contacts.json file is being pulled from the correct location. Its trying to filter on an initial list of contacts that is undefined.
