### ISSUE TITLE
Where is the kanban board code in Chapter 1?

### ISSUE THREAD

**Issue by sbefort** [pro-react/sample-code#4]
I only see the grocery list code.

**Comment by cassiozen** [comment]
The Kanbanboard is a separate repository. You can find it here: https://github.com/pro-react/kanban-app

**Comment by marcvc** [comment]
How can I see the actual code from the various chapter? I tried the following: 
~\Documents\GitHub> git clone git@github.com:pro-react/kanban-app.git
Cloning into 'kanban-app'...
Warning: Permanently added 'github.com,192.30.253.113' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

What can I do to get to the actual code?
