### ISSUE TITLE
Need explanation for the value of value-attribute.

### ISSUE THREAD

**Issue by cblume** [pro-react/sample-code#6]
I don't under stand why `value={this.state.newItem}` is being used in [this example](https://github.com/pro-react/sample-code/blob/master/chapter%204/animation/app/App.js#L57). Our `state` doesn't have a property called `newItem`, so I'm obviously missing something, aren't I?

I appreciate your help and I really like your book!

**Comment by tudoistube** [comment]
<input type="text" value={this.state.newItem} 
                   onKeyDown={this.handleChange.bind(this)}/>
↓  
  handleChange(evt) {
    if(evt.key === 'Enter'){
      // Create a new item and set the current time as it's id
      let newItem = {id:Date.now(), name:evt.target.value}
      // Create a new array with the previous items plus the value the user typed
      let newItems = this.state.items.concat(newItem);
      // Clear the text field
      evt.target.value='';
      // Set the new state
      this.setState({items: newItems});
    }

  }
↓  
I think when onKeyDown is revoked, it gets newItem and return to the value of input tag.
I guess it is possible because of javascript's closure.
